---
title: "SMM047 Group Coursework 2025-26"
subtitle: "Group 07"
author:
  - "Abdulrahman Alolyan"
  - "Benjamin Evans"
  - "Amogh Sharma"
  - "Nivetha Subbiah"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output:
  html_document:
    self_contained: true
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
    code_folding: show
    theme: flatly
    highlight: tango
    df_print: paged
# runtime: shiny
---

# Key Information

## Background

This R Markdown document was created as part of a group assignment for SMM047 at
Bayes Business School, City St George's, University of London in Term 1 2025-26.

- _BE note: use
  `rmarkdown::render("MSc_AS-SMM634-Group4-Project.rmd", output_dir = "docs")`
  to render this document_

# Initial processing

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, message = FALSE, warning = FALSE,
  fig.align = "center", fig.width = 7, fig.height = 7,
  out.width = "100%"
)
```

```{r}
dir.create("fig", showWarnings = FALSE)
knitr::opts_chunk$set(
  fig.path   = "fig/",
  dpi        = 300,
  fig.width  = 6,
  fig.height = 4,
  dev        = "png"
)
knitr::opts_chunk$set(dev = "svglite")
```

```{r}
## dependencies / external librarys
library(quantmod)
```

```{r Download data}
# Download the data
getSymbols("^IXIC", from = "2018-01-01", to = "2024-12-31")
```

```{r Plot downloaded data}
IXIC_Adj <- na.omit(Ad(IXIC))
plot(IXIC_Adj)

# Calculate the ?
z_n = na.omit(log(IXIC_Adj / dplyr::lag(IXIC_Adj)))
plot(z_n)
```

# Element 1: data cleaning and standard test of normality

```{r Element 1}
#---------- Element 1: data cleaning and standard test of normality -----------#

library(summarytools)

summary_table <- descr(
  z_n,
  stats = c("mean", "sd", "skewness", "kurtosis"),
  transpose = TRUE,
  headings = FALSE,
  round.digits = 6
)
print(summary_table)


boxplot(z_n)


# # COVID: 10/04/2020-19/05/2020
#
IXIC_Adj <- IXIC_Adj[
  !((index(IXIC_Adj) >= "2020-04-10") &
    (index(IXIC_Adj) <= "2020-05-19"))
]
#
#
z_n = na.omit(log(IXIC_Adj / dplyr::lag(IXIC_Adj)))

plot(z_n)
boxplot(z_n)
```
